basic_auth:
  username: admin
  password: password

catalog:
  services: # catalog must advertise at least one service
    - id: github-repo
      name: GitHub repository service
      description: An instance of this service provides a repository which an app can write to and read from.
      bindable: true
      plans: # a service has one or more plans
        - id: public-repo
          name: free
          description: All repositories are public